apiVersion: v2
appVersion: v1.3.6
dependencies:
- condition: cassandra.enabled
  name: cassandra
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 11.x.x
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.x.x
- condition: mysql.enabled
  name: mysql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.x.x
- condition: elasticsearch.enabled
  name: elasticsearch
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 21.6.x
- condition: kafka.enabled
  name: kafka
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 30.x.x
description: 'Cadence is a distributed, scalable, durable, and highly available orchestration
  engine to execute asynchronous long-running business logic in a scalable and resilient
  way. This chart deploys Uber Cadence server components and web UI. '
home: https://cadenceworkflow.io/
icon: https://cadenceworkflow.io/img/cadence-logo.svg
keywords:
- cadence
- uber
- workflow
- orchestration
- workflow-engine
maintainers:
- name: Cadence Community
  url: https://github.com/cadence-workflow/cadence-charts
name: cadence
sources:
- https://github.com/cadence-workflow/cadence
- https://github.com/cadence-workflow/cadence-web
type: application
version: 1.1.0
